name: app
description: Customer mobile app

version: 1.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  go_router: ^15.1.2

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.1.4
  hive: ^2.2.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_keyboard_visibility: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  file: ^7.0.1
  flutter_portal: ^1.1.4
  flutter_native_splash: ^2.4.6
  dotted_border: ^3.0.1
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  # sentry_flutter: ^8.14.0
  pin_code_fields: ^8.0.1
  audioplayers: ^6.4.0
  permission_handler: ^12.0.0+1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_stripe: ^11.5.0
  socket_io_client: ^3.1.2
  flutter_datetime_picker_plus: ^2.2.0
  fl_chart: ^1.0.0
  url_launcher: ^6.3.1
  currency_text_input_formatter: ^2.3.0
  carousel_slider: ^5.0.0
  language_code: ^0.5.5
  flutter_html: ^3.0.0
  map_launcher: ^3.5.0

  
  
  intl_phone_number_input:
    git:
      url: https://github.com/mminhlequang/intl_phone_number_input.git
      ref: c47d3bf8c275f60687d81db4eb708957509df2e0
  internal_core:
    git:
      url: https://github.com/mminhlequang/internal_libs_flutter.git
      path: core/
      ref: 9ebecbeadacbe7cb259e29d8cf8c956ae43b2890
  internal_network:
    git:
      url: https://github.com/mminhlequang/internal_libs_flutter.git
      path: network/
      ref: 9ebecbeadacbe7cb259e29d8cf8c956ae43b2890

  network_resources:
    path: ../network_resources

  geolocator: ^14.0.1
  avatar_glow: ^3.0.1
  dotted_line: ^3.2.3
  country_codes: ^3.3.0
  geocoding: ^4.0.0
  visibility_detector: ^0.4.0+2
  sliding_up_panel: ^2.0.0+1
  infinite_listview: ^1.1.0
  flutter_rating_bar: ^4.0.1

dependency_overrides:
  http: ^1.3.0
  intl: ^0.20.2
  js: ^0.7.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_1024.png"
 
flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
    - assets/images/jpg/ 

